name: Status Badge Action

runs:
  using: "composite"
  steps:
    - name: Badge Content Setup
      id: setup_badge
      run: |        
        if [[ ${{ inputs.color == 'Diamond' }} ]]
        then
          color = "ccca6f"

        elif [[ ${{ inputs.color == "Gold" }} ]]
        then
          color = "ccac00"

        elif [[ ${{ inputs.color == "Silver" }} ]]
        then
          color = "bec9c4"

        else
          echo "Expected input value for status badge action: Diamond, Gold, Silver"
          exit 1
        fi

        echo ::set-output name=color::$(echo $color)    
        echo ::set-output name=sha::$(git rev-parse --verify HEAD)      
      shell: bash

    - name: Setup Badge
        uses: RubbaBoy/BYOB@v1.2.1
        with:
          NAME: ${{ inputs.badge_name }}
          LABEL: ${{ steps.setup_badge.outputs.sha }}
          #NAME: eks-terraform
          #LABEL: ${{ steps.setup_badge.outputs.sha }}
          STATUS: ${{ inputs.color }}
          COLOR: ${{ steps.setup_badge.outputs.color }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
